---
title: "Presentaciones"
author: " "
---

## Conferences & presentations

[Presentación Observatorio de Cohesión social](documents/conferencias/ocs_coes2020/ocs_coes.html) - Taller CEPAL-COES: ¿Cómo se define la cohesión y cómo se puede medir?; 9 Noviembre 2020.


[Reproducibilidad](documents/conferencias/coes2020_cienciabierta/02_reproducibilidad.html) - Panel Ciencia Abierta en Conferencia Desarrollo y Cohesión Social COES-DESOC 3 Noviembre 2020


Tokio LAINAC Conference - Enero 2020: Rethinking Inequalities: [¿Menos desigualdad, más injusticia?](https://juancarloscastillo.github.io/chilegapstime/docs/prestokio2020/castillo20202tokio.html#1)

[CEPAL 2019 Taller interno Cohesión Social](documents/CEPAL2019/pres01.html)

[Desigualdad, Justicia y Redistribución, Foro FACSO 2019](documents/foroFACSOnov2019/castillo2019forofacso.html)

[Colaboración y Ciencia Abierta (Seminario COES _Abrir la Academia_). 10 de Septiembre 2019, FEN Universidad de Chile.](documents/abrir-la-academia/presentacion.html)

Desigualdad Económica, Percepción de Meritocracia y Preferencias Redistributivas (Congreso Chileno de Sociología - Diciembre 2018) [(*link to presentation*)](https://juancarloscastillo.github.io/jc-castillo/documents/presentacion-final/present-panel-alas2018.html#1)

Meritocracia y redistribución en una sociedad desigual (Conferencia COES - Noviembre 2018) [(*link to presentation*)](https://juancarloscastillo.github.io/jc-castillo/documents/coes2018/castillo2018meritocracyCOES.html#1)

Open academic writing: An Atom-based workflow for social scientists (SocArxiv 2018 Conference - Maryland)[(*link to presentation*)](https://juancarloscastillo.github.io/jc-castillo/documents/atomworkflow/Xiringito_press.html#1)

Castillo,JC (2018) Perceptions and preferences about meritocracy in international comparison. Congress of the International Sociological Association - ISA (July 15-21). Toronto, Metro Toronto Convention Center [(to presentation)](documents/ISA2018presentation/castillo2018meritocracyISA.html).

Castillo, JC. & Jaime-Castillo, A. (2018) Reciprocity and Distributive Justice. Joint session organized for the Research Committee 42 (Social Psychology)  and 45 (Rational Choice) at the Congress of the International Sociological Association - ISA (July 15-21). Toronto, Metro Toronto Convention Center.

Castillo, JC. (2017) Percepciones y legitimación de la desigualdad: Mérito e Instituciones. Panel Congreso Latinoamericano de Sociología (Diciembre 2-7). Montevideo, Universidad de la República.

Castillo, JC. (2017) Meritocracia y preferencias redistributivas. Panel Conferencia COES (Noviembre 8-9. Viña del Mar, Universidad Adolfo Ibañez.

Castillo, JC. (2017) Meritocratic beliefs and economic inequality. Colloquium of Macro Sociology (Julio 12). Berlin, Humboldt University.

Castillo, JC. & Miranda, D. (2017) Class and Status as Predictors of Inclusive Attitudes Towards Immigrants, Minorities and Gender. 7th IEA International Research Conference (IRC) (June 28-30). Prague, Charles University.

Castillo, JC. (2016) Origen y atribuciones de la pobreza y desigualdad social (origins and atributions of poverty and social inequality). Session organizer, COES-LSE Conference "Inequalities". (Nov. 3-5). Santiago, Chile.

Castillo, JC (2016) Desigualdad y meritocracia (inequality and meritocracy). Presentation at the conference cycle "Catedra Investigación Santiago" (Oct. 19). Santiago, Chile.

Castillo, JC (2016) Meritocracia y explicaciones de la pobreza: Medición y vinculaciones (meritocracy and poverty explanations: measurement and links). Session organizer, "Congreso Chileno de Sociología" (October 11-14). Talca, Chile.

Castillo, JC. & Frei, R. (2016) Clases de atribuciones de riqueza y pobreza (class attributions of poverty and wealth). Paper presented at the "Congreso Chileno de Sociología" (October 11-14). Talca, Chile.

Castillo, JC. (2016) Meritocracia y preferencias redistributivas (meritocracy and redistributive preferences). Research colloquium Institute of Sociology, Pontificia Universidad Católica de Chile (Oct. 4). Santiago, Chile.

Castillo, JC (2016) Economic Inequality, Distributive Preferences and Political Outcomes (I & II). Sessions organized for the Research Committee 42 (Social Psychology) at the Congress of the International Sociological Association - ISA (July 9-14). Vienna, Austria.

Castillo, JC (2016) Inequality, Distributive Preferences and Types of Participation in Latin America. Paper presented at the Congress of the International Sociological Association - ISA (July 9-14). Vienna, Austria.

Castillo, JC. & Miranda, D. (2015) Origen social, conocimiento cívico y participación en la escuela. CIEP - Congreso Internacional de Educación y Pobreza (January 08 - 10) Villarrica, Chile.

Miranda, D. & Castillo, JC.  (2015) Lo civil y lo civico: Hacia un modelo conceptual y de medición de ciudadanía escolar. CIEP - Congreso Internacional de Educación y Pobreza (January 08 - 10) Villarrica, Chile.

Castillo, JC., Olivos, F. & Azar. A. (2015) What is a just pension? A factorial survey approach. WAPOR (June 16-19) Buenos Aires, Argentina.

Castillo, J. (2014) Inequality, justice beliefs and political participation in Latin America. Paper presented at the Congress of the International Sociological Association - ISA (July 13-19). Yokohama, Japan.

Bargsted, M., Castillo, J. & Somma, M. (2014) Political trust in Latin America. Paper presented at the WAPOR Latin America Conference (18-20 June). Santiago de Chile.

Castillo, J. (2014) Economic inequality and Social Justice in Latin America. Poster presented at the Herrenhausen Konferenz: Re-thinking social inequality (May 12-14). Hannover, Germany.

Bargsted, M., Castillo, J. & Somma, M. (2014) Political trust in Latin America. Paper presented at the authors' workshop of the Handbook of Political Trust (May 15-18). Goethe Universität Frankfurt am Main, Germany.

Castillo, J., Tham, M. & Palacios, D. (2013) Desigualdad, justicia distributiva y participación política en Chile. Paper presented at the “Congreso de la Asociación Latinoamericana de Sociología – ALAS” (September 29 –October 4). Santiago de Chile.

Miranda, D., Castillo, J., Cox, C., Bascopé, M., & Bonhomme, J. (2013) Autoritarismo y Valores Democráticos en Estudiantes Latinoamericanos. Paper presented at the “Congreso de la Asociación Latinoamericana de Sociología – ALAS” (September 29 – October 4). Santiago de Chile.

Zmerli, S. & Castillo, J. (2013) Income inequality and social trust in Latin American societies. Paper presented at the “7th ECPR General Conference”, Panel: Dismantling Democracy: The Challenge of Inequality to Political Engagement. (September 4-7). Bordeaux.

Miranda, D., Castillo, J., Cox, C., Bascopé, M., & Bonhomme, J. (2013) Socioeconomic background and expected political participation at school: individual and contextual mechanisms. Paper presented at the summer school “Rising Inequalities and their impacts on Societies” (September 2-6). Levico, Italy.

Castillo, J., Miranda, D., Bonhomme, M., Cox, C. & Bascopé, M. (2013) Mitigating the participation gap from the school: The role of civic knowledge and classroom climate. Paper presented at the research colloquium of the Data Processing and Research Center, International Association for the Evaluation of the Educational Achievement (IEA). (August 7). Hamburg, Germany.

Miranda, D., Castillo, J., Cox, C.,  Bascopé, M., & Bonhomme, J.  (2013) Factors related to an open classroom climate and its impact on civic and expected political participation. Paper presented at the ”XV Comparative Education World Congress: New Times, New Voices” - WCCES (June 24-28). Buenos Aires, Argentina.

Castillo, J., Madero, I., Miranda, D. & Escobar, J. (2012) Education, equity and distributive beliefs: Evidence from the chilean case. Paper presented at the International Sociological Association - ISA Forum (August 1-4). Buenos Aires.

Castillo, J., Cox, C., Miranda, D., Bascopé, M., & Escobar, J. (2012) Desigualdad económica y cambios en las expectativas de participación de estudiantes en Chile. Paper presented at the ”Congreso Interdisciplinario de Investigación en Educación” - CIIE (August 23-24). Santiago de Chile.

Castillo, J., Cox, C., Miranda, D., Bascopé, M., & Escobar, J. (2012) Civic knowledge and political participation. Six Latin American countries in comparative perspectives. Paper presented at the International Sociological Association - ISA Forum (August 1-4). Buenos Aires.

Zmerli, S. & Castillo, J. (2012) Income inequality and political support: How objective and subjective inequality affect Latin Américan democracies. Paper presented at the Annual Scientific Meeting of the  International Society of Political Psychology – ISPP (July 5-9). Chicago.

Castillo, J., Cox, C., Miranda, D., Bascopé, M., & Escobar, J. (2012) Social inequality and changes in students' expected political participation in Chile. Paper presented at the Annual Scientific Meeting of the  International Society of Political Psychology – ISPP (July 5-9). Chicago.

Castillo, J., Cox, C., Miranda, D., Bascopé, M., Madero, I. & Escobar, J. (2012) Social origin and citizenship participation in Latin American schools. Paper presented at AERA Conference (April 13-17). Vancouver.

Castillo, J., Cox, C., Miranda, D., Bascopé, M., Madero, I. & Escobar, J. (2011) Actitudes hacia la democracia en estudiantes chilenos. Primer Congreso Nacional de Ciencias Sociales y Educación. Valparaíso: Universidad Católica de Valparaíso

Castillo, J., Salamovich, A. & Madero, I. (2011) Clivajes partidarios y preferencias distributivas. IV Congreso Nacional de Psicología. Santiago: Universidad de Chile.

Castillo, J., Salamovich, A. & Miranda, D. (2011) Partisan cleavages and distributive preferences: A cross sectional time comparison. Poster presented at the “Annual Scientific Meeting of the  International Society of Political Psychology – ISPP” (July 9-12). Istanbul: Bilgi University.

Castillo, J., Miranda, D. & Torres, P. (2011) Authoritarianism, Social Dominance & Trust in Public Institutions. Paper presented at the “Annual Scientific Meeting of the  International Society of Political Psychology – ISPP” (July 9-12). Istanbul: Bilgi University.

Castillo,J., Miranda, D. & Madero, I. (2011). Todos somos de clase media: Sobre el estatus social subjetivo en Chile. Paper presented at the “VI Congreso Nacional de Sociología – Pre ALAS 2011” (Apr. 13-15). Valparaíso: Universidad de Playa Ancha.

Castillo, J. & Miranda, D. (2010) Cambios en la relación entre religión e identidad política en Chile. (Changes in the relationship between religion and political identity in Chile). Presentation at the international seminar "Jóvenes, cultura y religión". Santiago: P. Universidad Católica de Chile.

Castillo, J. (2010)  Is inequality becoming just? Changes in public opinion about economic inequality in Chile. Paper presented at the "XXIX International Congress of the Latin American Studies Association" (Oct. 6-9). Toronto: Sheraton Conference Center.

Castillo, J. (2010) Higher salaries but stable inequality? A cross-sectional comparison of attitudes towards economic distribution. Paper presented at the "13th biennal conference of the International Society for Justice Research" (Aug. 21-24). Banff (Canada): The Banff Centre.

Castillo, J., Miranda, D. & Carrasco, D. (2010) Percepción de la desigualdad económica en Chile: Medición, determinantes y sesgos. (Perception of economic inequality in Chile: Measurement, determinants and biases). Presentation at the symposium "Tendencias emergentes de la (des) igualdad social: Desafíos para Chile y América Latina". Santiago: Universidad de Santiago.

Castillo, J. (2010). Cambios en la percepciones de la desigualdad económica en Chile (Changes in the perceptions of economic inequality in Chile). Presentation at the conference "La desigualdad: Legitimación y conflicto en las sociedades latinoamericanas". (July 21-24). Santiago: Universidad Alberto Hurtado.

Castillo, J. (2009) Herkunftsbedingte Disparitäten im Hochschulzugang in Chile und Deutschland (Desigualdades de origen social en el ingreso a la Universidad en Chile y en Alemania). Presentación en la conferencia “Herausforderungen der Globalisierung” (Nov. 20-21) Berlin: Iberoamerikanisches Institut.

Castillo, J. (2009). Perception and Legitimacy of Economic Inequality in Chile. Paper presentad at “5th ECPR General Conference” (Sept. 10-12). Potsdam: Potsdam University.

Castillo, J. (2009). What are Just Salaries for Different Occupations in Chile? Paper presentado en el “21st World Congress of Political Science – IPSA” (July 12-16). Santiago de Chile: Universidad de Chile.

Castillo, J. & Schneider, S., &. (2009). The Legitimacy kf Social Inequality in Comparative Perspective: Do People and Countries Differ in their Poverty Attributions? Paper presentado en el “21st World Congress of Political Science – IPSA” (July 12-16). Santiago de Chile: Universidad de Chile.

Schneider, S. & Castillo, J. (2009) Social Justice and Political Participation. Paper presentado (por el primer autor) en la “32nd Conference of the International Society of Political Psychology – ISPP” (July 14-17). Dublin: Trinity College.

Castillo, J. (2009). Consensus and Legitimacy of Earnings Inequality. Presentación en el  “International Social Justice Project Workshop” (May 6-10). Haifa: Haifa University, Israel.

Castillo, J. (2009). ¿Consenso o Conflicto acerca de la Distribución? La Legitimación de la Desigualdad Económica en Chile en Perspectiva Comparada. Paper presentado en la “2nd Latin American Conference of the World Association for Public Opinion Research” (April 22-24). Lima: Universidad Católica.

Castillo, J. (2008). Legitimación de la Desigualdad Económica en Chile. Presentación en la Universidad Academia de Humanismo Cristiano (December 10th), Santiago de Chile.

Castillo, J., Gerlitz, J., & Schrenker, M. (2008). Perception and Legitimacy of Income Inequality in International Comparison. Paper presentado en la “APSA Annual Conference” (Aug. 28-31). Boston: Conference Center

Castillo, J. (2008). On the Justice of Occupational Earnings in Chile: A Factorial Survey Analysis. Presentación en la “12th Conference of the International Society for Justice Research” (August 14-17). Adelaide: Flinders University.

Castillo, J., & Schneider, S. (2008). The Legitimacy of the Distributive System: A Comparison of Germany and Chile. Paper presentado en la “31st Conference of the International Society of Political Psychology – ISPP” (July 9-12). Paris: Sciences Po.

Castillo, J., Mühleck, K., & Wegener, B. (2008). The Empirical Approach to the Study of Social Justice: A Research Agenda for Latin America. Paper presentado en la conferencia "Intra- and inter- generational Transmission of Inequality" (Feb. 28-29). Mexico: Regional Bureau for Latin America and the Caribbean of United Nations Development Program (RBLAC-UNDP).

Castillo, J. (2007). Explanations of Poverty: A Comparison of Germany, the Czech Republic and Chile. Persentación en el “International Social Justice Project Workshop” (April 27-28). Budapest: Social Sciences Faculty, Eötvös Loránd University.

Castillo, J. (2007). Legitimation and Justice Ideologies in Contexts of Extreme Economic Inequalities. Paper presentado en la “30th Conference of the International Society of Political Psychology (July 4-7)”. Portland: Embassy Suites Hotel.

Castillo, J. (2007). Justice Ideologies and Attributions of Poverty in Comparative Perspective. Presentación en la conferencia "Law and Society in the 21st Century" (July 15-28). Berlin: Humboldt University.

Castillo, J. (2006). Justice Ideologies in Highly Unequal Contexts. The Case of Chile in Comparative Perspective. Poster presentado en la “11th  Conference of the International Society for Justice Research” (August 2-5). Berlin: Humboldt University.
