---
title: "Tesis"
author: " "
---

- Para quienes están realizando su Seminario o Tesis conmigo en FACSO / Universidad de Chile, ver detalles [acá](/post/seminarios/)


### *Tesis guiadas*



- Beck, G. (2019) Explorando la asociación entre redes de contacto ocupacionales y la justificación de la desigualdad social en Chile. Magíster en Sociología, P. Universidad Católica de Chile.

- Yañez, R. (2019) Construcción de juicios de justicia y emergencia de sentimientos de injusticia frente a la desigualdad social. Doctorado en Sociología, EHESS Paris (codirector).

- Iturra, J. (2018) Estatus social subjetivo y Percepción de meritocracia: El caso de Chile. Magíster en Sociología, P. Universidad Católica de Chile.

- Rojas, S. (2018) La dimensión subjetiva de la desigualdad de género en ingresos: Factores individuales asociados a evaluación de lo percibido y lo justo. Magíster en Sociología, P. Universidad Católica de Chile.

- Miranda, D. (2018) The civic and civil dimensions of youth participation. Doctorado en sociología, P. Universidad Católica de Chile.

- Plaza, A. (2018) Movilidad social y preferencias por la redistribución: Efectos individuales y contextuales. Magíster en Sociología, P. Universidad Católica de Chile.

- Franetovic, G. (2018) Desigualdad, desarrollo económico y preferencias redistributivas en América Latina. Magíster en Sociología, P. Universidad Católica de Chile.

- Muñoz, E. (2018) Evaluaciones de justicia distributiva sobre las pensiones de vejez en Chile. Magíster en Sociología, P. Universidad Católica de Chile.

- Castro, F. (2018) ¿Menos confianza, menos Estado? El impacto de la corrupción sobre las preferencias redistributivas. Magíster en Sociología, P. Universidad Católica de Chile.

- Sandoval, D. (2017) Merezco estar aquí: Un estudio multinivel sobre la relación entre meritocracia y educación. Magíster en Sociología, P. Universidad Católica de Chile.

- Montedónico, S. (2017) Contexto Polı́tico Institucional y Preferencias Redistributivas en América Latina. Magíster en Sociología, P. Universidad Católica de Chile.

- Acevedo, F. (2017) Compromiso Cívico Juvenil en Chile: una aproximación desde los recursos. Magíster en Sociología, P. Universidad Católica de Chile.

- Placencio, M. (2016) Legitimidad del Sistema Económico y Participación Ciudadana: Una aproximación a la relación entre percepciones individuales y actividad política en Chile. Magíster en Sociología, P. Universidad Católica de Chile.

- Viertel, F. (2016) Medición en ciudadanía: Equivalencia y propiedades psicométricas de una escala de percepción en estudiantes. Magíster en Medición, Escuela de Psicología, P. Universidad Católica de Chile.

- Santander, E. (2015) ¿Qué puede hacer la cultura de la escuela para aumentar la participación política de sus estudiantes? Magíster en Sociología, P. Universidad Católica de Chile.

- Torres, A. (2014) Aspectos subjetivos de la meritocracia y su relación con la percepción de desigualdad en Chile. Magíster en Psicología Social-Comunitaria, P. Universidad Católica de Chile.


### *Lector/comité evaluador*

- Nuñez, R. (2017) Cambio cultural en Chile: un análisis sobre los valores posmaterialistas, la justificación a la homosexualidad y al aborto, desde 1990 al 2011. Magíster en Sociología, P. Universidad Católica de Chile.

- Lozier. D. (2017) Comportamiento ambiental en Chile: Factores situacionales y efecto contexto en el nivel de adopción de conductas ecológicas en la región Metropolitana. Magíster en Sociología, P. Universidad Católica de Chile.

- Velasquez, D. (2017) Acción policial en las huelgas en Chile 2010-2015: La disputa por el orden productivo. Magíster en Sociología, P. Universidad Católica de Chile.

- Fromm, G. (2017) A structural model of educational leadership and contexts influence over teachers’ efficacy beliefs. Doctorado en Educación, Pontificia Universidad Católica de Chile.

- Villarroel, N. (2016) Stability and change in political right-wing groups in Chile: understanding the shift among right wingers to the center. Magíster en Psicología Social, Pontificia Universidad Católica de Chile.

- Meza, F. (2016) Confianza política y conocimiento cívico en adolescentes chilenos de octavo básico. Magíster en Sociología, P. Universidad Católica de Chile.

- Espinoza, A. (2015) La productividad y la colaboración en el reconocimiento cientı́fico de los astrónomos de Chile. Magíster en Sociología, P. Universidad Católica de Chile.

- Valenzuela, D. (2015) Coexistencia entre prácticas de cuidado y de explotación. Magíster en Sociología, P. Universidad Católica de Chile.

- Trebilcok, M. (2015) Hijos, amigos y mineros: Vínculos de cohesión social en el trabajo. Doctorado en Sociología, P. Universidad Católica de Chile.

- Ibañez, S. (2015) La legitimación de las desigualdades Salariales. Doctorado en Sociología, Universidad Alberto Hurtado.

- Ortúzar, L. (2013) Creencias de Mundo Justo en Jóvenes Chilenos según status social. Magíster en Psicología Social, P. Universidad Católica de Chile.

- Gómez, K. (2013) Microfinanzas en Chile: Su impacto en el Capital Social, Empoderamiento y Equidad de Género, Magíster en Psicología Social, P. Universidad Católica de Chile.
