---
title: "Formación ciudadana I: Socialización política y experiencia escolar - Chile en contexto internacional"
subtitle: FONDECYT Regular 2012-2015
summary: "Este es un primer proyecto FONDECYT (2012-2015) sobre formación ciudadana en que trabajamos junto a Cristián Cox (investigador principal) y Daniel Miranda. El producto central es el libro Aprendizaje de la Ciudadanía"
tags:
- Fondecyt
date: "2015-03-31T00:00:00Z"
output:
  html_document:
  toc: true
  toc_float: true
  toc_collapsed: true
# Optional external URL for project (replaces project detail page).
external_link: ""

image:
#  caption: Photo by rawpixel on Unsplash
  focal_point: Smart

links:
#- icon: twitter
#  icon_pack: fab
#  name: Follow
#  url: https://twitter.com/georgecushen
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""

# Slides (optional).
#   Associate this project with Markdown slides.
#   Simply enter your slide deck's filename without extension.
#   E.g. `slides = "example-slides"` references `content/slides/example-slides.md`.
#   Otherwise, set `slides = ""`.
#slides: example
---
# Resumen
 
La hipótesis general de investigación es que el currículo escolar, junto a una serie de factores
contextuales, poseen una influencia en la formación cívica y ciudadana. El contraste de esta
hipótesis requiere por un lado un análisis de los contenidos curriculares, y por otro de factores
contextuales a nivel familiar (nivel socioeconómico, capital cultural), nivel curso (variables
asociadas a los docentes y la composición del curso), nivel escuela (características
sociodemográficas y preocupación por temas cívico/ciudadanos), y nivel comparativo de países
(indicadores socioeconómicos y de cultura política). Por lo tanto, la investigación se define por
el desarrollo de dos líneas de trabajo, curricular y contextual, con lo que se espera dar
respuesta a la pregunta de investigación. Dentro de los factores contextuales se dará un
acento especial al rol de los docentes, complementando el análisis de bases de datos
secundarias con el levantamiento de información cualitativa de prácticas docentes en aula.

# Documentos

- [Formulación propuesta](formulacion-fondecyt-ciudadania1.pdf)
- [Informe Resultados](1120630E2014.pdf)

# Equipo

**Investigador principal** : Cristián Cox (Facultad Educación Universidad Católica).

**Coinvestigadores**

- Juan Carlos Castillo, Mide UC
- Daniel Miranda, Psicología UC
- Martín Bascopé, Facultad de Educaciṕon UC

**Asistentes de investigación:**

- Macarena Bonhomme

# Tesistas

- Eduardo Santander, Magister Sociología UC - Profesor:  Juan Carlos Castillo
- Federico Viertel, Magister Medición UC - Profesor:  Juan Carlos Castillo
