---
title: "Social justice and citizenship participation: An international comparison with focus on the case of Chile "
subtitle: FONDECYT Iniciación 11121203 (2013-2015).
summary: Este proyecto FONDECYT tuvo como principal objetivo analizar el rol que juegan las percepciones y creencias respecto de la desigualdad económica en distintas formas de participación política y ciudadana.
tags:
- Fondecyt
- Justicia Distributiva
date: "2013-03-31T00:00:00Z"

# Optional external URL for project (replaces project detail page).
external_link: ""

image:
#  caption: Photo by rawpixel on Unsplash
  focal_point: Smart

links:
#- icon: twitter
#  icon_pack: fab
#  name: Follow
#  url: https://twitter.com/georgecushen
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""

# Slides (optional).
#   Associate this project with Markdown slides.
#   Simply enter your slide deck's filename without extension.
#   E.g. `slides = "example-slides"` references `content/slides/example-slides.md`.
#   Otherwise, set `slides = ""`.
#slides: example
---
# Resumen

El proyecto de investigación “Justicia distributiva y participación ciudadana” se desarrolló entre los años 2012 y 2015, y tuvo como principal objetivo analizar el rol que juegan las percepciones y creencias respecto de la desigualdad económica en distintas formas de participación política y ciudadana. Este objetivo se construye en base a evidencia de una serie de estudios previos. En primer lugar, existe amplia literatura que documenta la asociación entre desigualdad económica y participación política, en el sentido que aquellos con mayores recursos (como tiempo, dinero, capacidades cognitivas) reportan consistentemente mayores niveles de participación. Tal relación sin duda representa una amenaza a los objetivos centrales de la democracia en términos de capacidades igualitarias de voz y representación política (un individuo, un voto). En segundo lugar, investigaciones en el área de justicia distributiva señalan que existe una gran variabilidad en la población tanto en percepciones como en creencias respecto de la desigualdad. Estudios en el área de la percepción de desigualdad muestran que son las personas de mayor nivel  socioeconómico los que identifican mayores brechas salariales entre ocupaciones de distinto estatus, así como también son aquellos que justifican una mayor desigualdad salarial. Por lo tanto, tomando en cuenta la evidencia previa surge la pregunta de en qué medida las percepciones y creencias respecto de la desigualdad se relacionan con mayores capacidades de acción y representación ciudadana.

Para poder lograr sus objetivos, en primer lugar se realizó un análisis de distintas encuestas donde había indicadores relevantes de los temas en estudio (justicia y participación). Ya que este no es un tema que cuente con un amplio respaldo en investigaciones anteriores, en una segunda etapa se diseñó una encuesta con indicadores específicos en temas de desigualdad, justicia y participación. Esta encuesta fue aplicada cara a cara a una muestra de alrededor de 1200 individuos representativos del país durante el año 2013. Además, durante el año 2014 se aplicó nuevamente a los residentes en Santiago, de manera de evaluar estabilidad o cambio en las variables presentes en el estudio. La encuesta es la primera de este tipo en el país en esta temática.

Los análisis de los datos, tanto de otros estudios como también los basados en la encuesta diseñada para este proyecto, arrojan una serie de resultados relevantes. En primer lugar es interesante constatar que, tal como revelan otros estudios, la participación ciudadana se asocia a los recursos de las personas. En otras palabras, quienes más participan son aquellos con más dinero y mayor nivel educacional. Segundo, se constata que en Chile existen grandes diferencias generacionales en las modalidades de participación: mientras los mayores participan preferentemente en actividades de política formal (voto, partidos políticos), los más jóvenes se orientan por manifestarse en actividades como marchas y/o protestas. Tercero, lo que las personas piensan respecto a la justicia distributiva tiene un impacto en los niveles de participación ciudadana, tanto en voto como en protesta. Sin embargo, es mucho más significativa la participación en protestas para aquellos que califican como injusta la distribución económica en la sociedad.

Estos y otros resultados de la investigación han sido presentados en congresos internacionales y también en el marco de estadías de investigación en el extranjero. Además, dos prestigiosas académicas han visitado Chile para colaborar con el estudio: la profesora Leslie McCall de Northwestern University, Estados Unidos, y la profesora Sonja Zmerli, de la Universidad de Frankfurt, Alemania. Ambas participaron en seminarios de difusión del proyecto.

Los principales resultados de los estudios realizados en el marco de este proyecto han sido publicados en una serie de revistas científicas, tales como Social Science Research, Social Psychology Quarterly, Bulletin of Latin American Research, Revista de Ciencia Política y Revista Sociedad Hoy. Además, en el proyecto se han realizado cuatro tesis de magister y una de doctorado.

# Resultados

ver informe [aquí](resultados_iniciacion.pdf)


# Equipo

**Investigador principal** : Juan Carlos Castillo (Sociología - Universidad de Chile).

**Asistentes de investigación:**

- Daniel Miranda
