---
title: "Meritocracia en la escuela (EDUMER): Fundamentos morales del mercado educativo y sus implicancias para la formación ciudadana en Chile"
subtitle:  FONDECYT Regular 1210847 (2021-2024).
summary: "Este proyecto FONDECYT regular (2021-2024) aborda las percepciones y valoraciones de estudiantes de ciclo básico y medio en relación a aspectos específicos del mercado educativo vinculados a meritocracia, como son la selección, la competencia y el esfuerzo individual. Junto a ello, este proyecto pone énfasis en las posibles contradicciones existentes entre la valoración de aspectos meritocráticos individuales y el énfasis en normas colectivas y de cohesión social que caracterizan a la formación ciudadana"
tags:
- Fondecyt
date: "2021-03-31T00:00:00Z"

# Optional external URL for project (replaces project detail page).
external_link: ""

image:
#  caption: Photo by rawpixel on Unsplash
  focal_point: Smart

links:
#- icon: twitter
#  icon_pack: fab
#  name: Follow
#  url: https://twitter.com/georgecushen
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""

# Slides (optional).
#   Associate this project with Markdown slides.
#   Simply enter your slide deck's filename without extension.
#   E.g. `slides = "example-slides"` references `content/slides/example-slides.md`.
#   Otherwise, set `slides = ""`.
#slides: example
---

# Resumen


Una de las características de Chile como caso de estudio a nivel internacional son las desigualdades en logro académico. Estas desigualdades en la etapa escolar han sido asociadas a la privatización/comodificación del sistema educacional Chileno, que desde las reformas neoliberales implementadas durante y desde la dictadura han profundizado políticas basadas en subsidio a privados, incentivos al logro, competencia, selección y segregación (Corvalán, Carrasco y García-Huidobro, 2017; Valenzuela, Bellei y de los Rios, 2013). Basándose en conceptos y evidencias de la sociología económica y de la educación, este proyecto aborda las percepciones y valoraciones de estudiantes de ciclo básico y medio en relación a aspectos específicos del mercado educativo vinculados a meritocracia, como son la selección, la competencia y el esfuerzo individual. Junto a ello, este proyecto pone énfasis en las posibles contradicciones existentes entre la valoración de aspectos meritocráticos individuales y el énfasis en normas colectivas y de cohesión social que caracterizan a la formación ciudadana (Cox & Castillo, 2015; Resh & Sabbagh, 2013, 2017). El proyecto contempla en sus primer año una fase cualitativa de entrevistas y grupos de discusión abarcando profesores, familias y estudiantes. Los años posteriores se enfocarán en el desarrollo del estudio panel ​ “Justicia educacional y ciudadanía”​ , que seguirá durante tres años a cohortes de 6to, 8vo y 2do medio de 30 escuelas del país.

# Documentos



# Equipo

**Investigador principal** : Juan Carlos Castillo (Sociología - Universidad de Chile).

**Co-investigadores**:

- Nicolás Angelcos (Sociología- Universidad de Chile)
- Camila Moyano (Centro de Justicia Educacional, Universidad Católica)
-  Mauricio Salgado (Sociología - Universidad Andrés Bello).

**Asistentes de investigación:**
- Adolfo Maza
- Francisco Molina
- Kevin Carrasco


**Periodo**: 2021-2024

# Tesistas
