---
title: "Publicaciones"
author: " "
---

## En desarrollo

- Redes de contacto y justificación de la desigualdad
social: Una exploración desde el caso chileno, con Guillermo Beck (autor principal) y Matías Bargsted. Enviada.

- Taking from the rich or giving to the poor: The two faces of support for redistribution (with Efraín García-Sánchez)

- Redistributive preferences in unequal contexts: Changes in Latin America between 2008 and 2018 - con Gonzalo Franetovic (submitted)

- Perceptions and Preferences about Meritocracy in International Comparison  [(*link to ISA 2018 presentation*)](https://juancarloscastillo.github.io/jc-castillo/documents/ISA2018presentation/castillo2018meritocracyISA.html#1)

- Equality or Insurance? The underlying motives for supporting social policy in Latin America (with Jose de Amesti - 1st author, Luis Maldonado & Jorge Atria). Submitted.

- Do people perceive more inequality when more inequality exists? (with Martin Schröder). Revise & Resubmit.

<br>

### Peer-reviewed journal articles

(If you are looking for copies of my papers, check my site in [Researchgate](https://www.researchgate.net/profile/Juan_Castillo5/contributions)).

- Atria J, Castillo J, Maldonado L, Ramirez S. (2020) Economic Elites’ Attitudes Toward Meritocracy in Chile: A Moral Economy Perspective. American Behavioral Scientist 64(9),1219-1241. [https://doi.org/10.1177/0002764220941214](https://journals.sagepub.com/doi/10.1177/0002764220941214)

- Frei, R., Castillo, J. C., Herrera, R., & Suárez, J. I. (2020). ¿Fruto del esfuerzo? Los cambios en las atribuciones sobre pobreza y riqueza en Chile entre 1996 y 2015. Latin American Research Review, 55(3), 477–495. DOI: [http://doi.org/10.25222/larr.464](https://larrlasa.org/articles/10.25222/larr.464/)

-  Martínez, M. L., Cumsille, P., Loyola, I., & Castillo, J. C. (2020). Patterns of Civic and Political Commitment in Early Adolescence. The Journal of Early Adolescence, 40(1), 5–27. [https://doi.org/10.1177/0272431618824714](https://doi.org/10.1177/0272431618824714)

-   Miranda, D., Castillo, J. C., & Sandoval-Hernandez, A. (2020). Young Citizens Participation: Empirical Testing of a Conceptual Model. Youth & Society, 52(2), 251–271. [https://doi.org/10.1177/0044118X17741024](https://doi.org/10.1177/0044118X17741024)
<a href="https://www.researchgate.net/publication/320263594_Young_Citizens_Participation_Empirical_Testing_of_a_Conceptual_Model">
<i class="ai ai-researchgate fa-lg" style="font-size:20px;color:green"></i></a> [pdf]("documentos/papers/Miranda et al. 2017. Young Citizens Participation.pdf")

- Maldonado, L., Olivos, F., Castillo, J.C. et al. (2019) Risk Exposure, Humanitarianism and Willingness to Pay for Universal Healthcare: A Cross-National Analysis of 28 Countries. Social Justice Research 32, 349–383 [https://doi.org/10.1007/s11211-019-00336-6](https://link.springer.com/article/10.1007/s11211-019-00336-6)

- Castillo, J.C., Olivos, F. and Azar, A. (2019), Deserving a Just Pension: A Factorial Survey Approach*. Social Science Quarterly, 100: 359-378. [https://doi.org/10.1111/ssqu.12539](https://onlinelibrary.wiley.com/doi/abs/10.1111/ssqu.12539). <a href="https://www.researchgate.net/publication/328359653_Deserving_a_Just_Pension_A_Factorial_Survey_Approach">
<i class="ai ai-researchgate fa-lg" style="font-size:20px;color:green"></i></a>

- Castillo, JC. & Torres, A. , Atria, J & Maldonado, L. (2019) Meritocracia y desigualdad económica: Percepciones, preferencias e implicancias. Revista Internacional de Sociología 77(1)1-15 (ISI) [https://doi.org/10.3989/ris.2019.77.1.17.114](https://doi.org/10.3989/ris.2019.77.1.17.114).
<i class="ai ai-open-access fa-lg" style="font-size:20px"></i>
<a href="https://www.researchgate.net/publication/325225032_Meritocracia_y_desigualdad_economica_Percepciones_preferencias_e_implicancias_Meritocracy_and_Economic_inequality_Perceptions_preferences_and_implications">
<i class="ai ai-researchgate fa-lg" style="font-size:20px;color:green"></i></a>
<a href="https://osf.io/preprints/socarxiv/qkpu4/">
<i class="ai ai-osf fa-lg" style="font-size:20px;color:blue"></i></a>


- Atria, J., Ramírez, S., Castillo, JC. & Maldonado, L. (2018) Studying meritocracy in an unequal context: Perspectives from chilean scholars. _Universum_ 34(2)127-145 (SCOPUS)  [DOI 10.4067/S0718-23762019000200127 ](http://dx.doi.org/10.4067/S0718-23762019000200127 ).<i class="ai ai-open-access fa-lg" style="font-size:20px"></i>

- Azar, A., Maldonado, L., Castillo, JC & Atria, J. (2018)
“Income, Egalitarianism, and Attitudes Towards Healthcare Policy: A Study on Public Attitudes in 29 Countries” _Public Health 148:59-69_ [https://doi.org/10.1016/j.puhe.2017.09.00](https://doi.org/10.1016/j.puhe.2017.09.007).

- Castillo, JC & Rivera,M. (2018) Poverty and wealth attributions: A second order confirmatory factor analysis model. Psykhe 27(2) [http://dx.doi.org/10.7764/psykhe.27.2.1152](http://dx.doi.org/10.7764/psykhe.27.2.1152) (SCOPUS).
<a href="http://www.psykhe.cl/index.php/psykhe/article/view/1152/pdf_113"><i class="ai ai-open-access fa-lg" style="font-size:20px"></i>
<a href="https://www.researchgate.net/publication/326637297_Common_dimensions_for_poverty_and_wealth_attributions">
<i class="ai ai-researchgate fa-lg" style="font-size:20px;color:green"></i></a>
<a href="https://osf.io/preprints/socarxiv/5xnrd/">
<i class="ai ai-osf fa-lg" style="font-size:20px;color:blue"></i></a>

- Atria, J., Amenábar, J., Sanchez, J., Castillo, JC & Cociña, M. (2017) Investigando a la élite económica: Lecciones y desafíos a partir del caso de Chile. Cultura, Hombre y Sociedad 27(2)5-36 [http://dx.doi.org/10.7770/cuhso-v27n2-art1244.](http://dx.doi.org/10.7770/cuhso-v27n2-art1244)(Scielo).
<i class="ai ai-open-access fa-lg" style="font-size:20px"></i>
<a href="https://www.researchgate.net/publication/322211841_Investigando_a_la_elite_economica_Lecciones_y_desafios_a_partir_del_caso_de_Chile_Researching_the_economic_elite_lessons_and_challenges_from_the_Chilean_case">
<i class="ai ai-researchgate fa-lg" style="font-size:20px;color:green"></i></a>
[link to pdf](https://scielo.conicyt.cl/pdf/cuhso/v27n2/0719-2789-cuhso-27-02-00005.pdf)

- Guerra, C. & Castillo, J (2016) Sintomatología en adolescentes victimizados sexualmente: El rol del apoyo de la familia y del grupo de pares. Revista sobre la infancia y la adolescencia, 11:66-80 (Latindex) [link](https://polipapers.upv.es/index.php/reinad/article/view/4478/6797)

- Castillo, J. (2016) Public opinion about just salaries in Chile: An exploratory study based on a factorial survey. Cuadernos ISUC 1(2)1:28 [link](http://sociologia.uc.cl/wp-content/uploads/2016/12/articulo-juan-carlos-castillo.pdf).

-   Schneider, S. M., & Castillo, J. C. (2015). Poverty Attributions and the Perceived Justice of Income Inequality: A Comparison of East and West Germany. Social Psychology Quarterly, 78(3), 263–282. [https://doi.org/10.1177/0190272515589298](https://doi.org/10.1177/0190272515589298)(ISI)[pdf]
("documents/papers/Schneider y Castillo - 2015 - Poverty Attributions and the Perceived Justice.pdf")

- Bascopé, Martín, Bonhomme, Macarena, Cox, Cristián, Castillom, Juan Carlos, & Miranda, Daniel. (2015). Curricular guidelines and citizenship attitudes in Latin American students: a comparative analysis. Revista Latinoamericana de Ciencias Sociales, Niñez y Juventud, 13(2), 1169-1190. [https://doi.org/10.11600/1692715x.13243280814](https://doi.org/10.11600/1692715x.13243280814).[pdf](https://www.researchgate.net/publication/274250465_Citizenship_Education_in_Latin_America_Priorities_of_School_Curricula)

- Castillo, J. , Joignant, A., Palacios, D., & Tham, M. (2015)  Inequality, distributive justice and political participation. Bulletin of Latin American Research 34(4)486-50 [https://doi.org/10.1111/blar.12369](https://doi.org/10.1111/blar.12369)(ISI) <i class="ai ai-open-access fa-lg" style="font-size:20px"></i>
[pdf](documents/papers/Castilloetal2015InequalityJusticePoliticalPar.pdf)

- Zmerli, S. & Castillo, J. (2015)  Inequality and political trust. How objective and subjective inequality affects Latin American democracies. Social Science Research 52, 179-192 [https://doi.org/10.1016/j.ssresearch.2015.02.003](https://doi.org/10.1016/j.ssresearch.2015.02.003) (ISI) [pdf](documents/papers/Zmerli & Castillo 2015 Inequality and political trust.pdf)

- Castillo, J., Cox, C., Miranda, D., Bascopé, M. & Bonhomme, M. (2014)  Mitigating the Political Participation Gap from the School: The Roles of Civic Knowledge and Classroom Climate. Journal of Youth Studies 18(1) 16-35 [https://doi.org/10.1080/13676261.2014.933199](https://doi.org/10.1080/13676261.2014.933199). (ISI) [pdf](documents/papers/castillo et al 2014 mitigating the political participation gap _ final published.pdf)

- Castillo, J. (2014) Actitudes hacia el trabajo y justicia salarial en Chile. Temas de la Agenda Pública 66, 33-44 <i class="ai ai-open-access fa-lg" style="font-size:20px"></i> [pdf](https://www.researchgate.net/publication/269928176_Actitudes_hacia_el_trabajo_y_justicia_salarial_en_Chile)

- Castillo, J., Madero, I. & Miranda, D. (2014) Educación, desigualdad y creencias distributivas: Evidencia del caso chileno. Sociedad Hoy 24 13-31 (Latindex) <i class="ai ai-open-access fa-lg" style="font-size:20px"></i> [pdf](https://www.researchgate.net/publication/264655431_Educacion_equidad_y_creencias_distributivas_Evidencias_del_caso_chileno)

- Castillo, J., Cox, C., Miranda, D. & Bascopé, M. & Bonhomme, M. (2014) Social inequality and changes in student's expected political participation in Chile. Education, citizenship & social justice 9(2) 140-156 [https://doi.org/10.1177/1746197914520650](https://doi.org/10.1177/1746197914520650). (SCOPUS).[pdf](documents/papers/castillo2014studentspoliticalparticipation.pdf)

- Factor, R., Castillo, J. & Rattner, A (2014) Procedural justice, religiosity and minorities. Police Practice and Research 15(2)130-142 (SCOPUS)[https://doi.org/10.1080/15614263.2013.874171](https://doi.org/10.1080/15614263.2013.874171)

- Preiss, D., Castillo, J., Flotts, P. & San Martin, E. (2013) Assessment of argumentative writing and critical thinking in higher education: Educational correlates and gender differences . Learning and Individual Differences 28, 193-203 (ISI)[link](https://www.researchgate.net/publication/259520367_Assessment_of_argumentative_writing_and_critical_thinking_in_higher_education_Educational_correlates_and_gender_differences)

- Preiss, D., Castillo, J., Grigorenko, H. & Manzi, J. (2013) Argumentative writing and academic achievement: A longitudinal study. Learning and Individual Differences 8,204-211 (ISI) [link](https://www.researchgate.net/publication/259520365_Argumentative_writing_and_academic_achievement_A_longitudinal_study)

- Castillo, J., Salamovich, A. & Madero, I. (2013) Clivajes partidarios y cambios en preferencias distributivas en Chile. Revista de Ciencia Política 33(2) 469-488 (ISI) <i class="ai ai-open-access fa-lg" style="font-size:20px"></i> [pdf](https://www.researchgate.net/publication/257823109_Clivajes_partidarios_y_cambios_en_preferencias_distributivas_en_Chile)

- Castillo, J., Miranda, D. & Madero, I. (2013) Todos somos de clase media: Sobre el estatus social subjetivo en Chile. Latin American Research Review 48(1) 155-173 (ISI) <i class="ai ai-open-access fa-lg" style="font-size:20px"></i> [pdf](https://www.researchgate.net/publication/236870281_Todos_somos_de_clase_media_Sobre_el_estatus_social_subjetivo_en_Chile)

- Castillo, J. (2013) Contrastes entre la desigualdad objetiva y subjetiva en Chile. Temas de la Agenda Pública 57, 1-15. (Latindex)<i class="ai ai-open-access fa-lg" style="font-size:20px"></i> [pdf](https://politicaspublicas.uc.cl/wp-content/uploads/2015/02/serie-n-57-contrastes-entre-la-desigualdad-economica-objetiva-y-subjetiva-en-chile.pdf)

- Castillo, J. Leal. P. & Madero, I. & Miranda, D. (2012) ¿Son los chilenos igualmente solidarios? La influencia de los recursos personales en las donaciones de dinero. Opiniao Publica (SCOPUS) <i class="ai ai-open-access fa-lg" style="font-size:20px"></i> [pdf](https://www.researchgate.net/publication/244484714_Son_los_chilenos_igualmente_solidarios_La_influencia_de_los_recursos_personales_en_las_donaciones_de_dinero).

- Castillo, J. (2012) La legitimidad de las desigualdades salariales. Una aproximación multidimensional. Revista Internacional de Sociología (ISI) <i class="ai ai-open-access fa-lg" style="font-size:20px"></i> [pdf](http://revintsociologia.revistas.csic.es/index.php/revintsociologia/article/viewFile/476/497)

- Madero, I. & Castillo , J. (2012) Sobre el estudio empírico de la solidaridad: Aproximaciones conceptuales y metodológicas. Polis.1(31) 391-409. (SCIELO) <i class="ai ai-open-access fa-lg" style="font-size:20px"></i> [pdf](https://scielo.conicyt.cl/scielo.php?script=sci_arttext&pid=S0718-65682012000100021)

- Castillo, J., Miranda, D. & Carrasco, D. (2012) Percepción de desigualdad económica en Chile: Medición, diferencias y determinantes. Psykhé 21(1) 99-114. (SCOPUS) <i class="ai ai-open-access fa-lg" style="font-size:20px"></i>[pdf](https://scielo.conicyt.cl/pdf/psykhe/v21n1/art07.pdf)

- Castillo, J. (2012) Is inequality becoming just? Changes in public opinion about economic distribution in Chile. Bulletin of Latin American Research, 31(1)1-18. (ISI) [pdf](documentos/papers/castillo 2012 is inequality becoming just - BLAR.pdf)

- Castillo, J. (2011) Legitimacy of inequality in a highly unequal context: evidence from the Chilean case. _Social Justice Research_ 24 (4) 314-340.(ISI) [pdf]("documents/papers/castillo 2011 legitimacy of inequality in a highly unequal context.pdf")

- Castillo, J. (2009). ¿Cuál es la Brecha Salarial Justa? Opinión Pública y Legitimación de la Desigualdad Económica en Chile. Estudios Públicos (113), 237-266.[link](https://www.cepchile.cl/cual-es-la-brecha-salarial-justa-opinion-publica-y-legitimacion-de-la/cep/2016-03-04/094825.html)

### Books, chapters & working papers

- Miranda & Castillo (2020) Cambios en la participación política de los escolares. En Alé, S., Duarte, K. & Miranda, D. (2020) Saltar el torniquete: Reflexiones desde las juventudes de Octubre. Santiago: Fondo de Cultura Económica.

- Castillo, JC. Miranda D, & Bonilla, A.(2020) Medición de actitudes hacia la igualdad de derechos entre géneros en pruebas internacionales: Implicancias respecto a su validez. En Manzi et al Validez de Instituciones Educacionales en Chile y Latinoamérica. Santiago: Ediciones UC - Preprint: <a href="https://osf.io/preprints/socarxiv/t87se/">
<i class="ai ai-osf fa-lg" style="font-size:20px;color:blue"></i></a>

- Castillo, J., Meneses, F., Iturra, J. & Maldonado, L. (2019) Cambios en percepción y justificación de desigualdad salarial en Chile entre 1999-2019. Revista Análisis del Año. Versión online en repositorio del proyecto [https://juancarloscastillo.github.io/chilegapstime](https://juancarloscastillo.github.io/chilegapstime)

- Maldonado, L., Castillo, J., Iturra, J., Atria, J., & Meneses, F. (2019). Meritocracia y redistribución en Chile: Señales de la opinión pública. [https://doi.org/10.17605/OSF.IO/G4EK8](https://doi.org/10.17605/OSF.IO/G4EK8)<a href="https://doi.org/10.17605/OSF.IO/G4EK8"><i class="ai ai-osf fa-lg" style="font-size:20px;color:blue"></i></a>. [Columna CIPER](https://www.ciperchile.cl/2019/12/06/la-demanda-por-igualdad-y-los-caminos-que-cuentan-con-amplio-respaldo-ciudadano/)

- Breznau, N., Rinke, E., Wuttke, A., Adem, M., Adriaans, J., Alvarez-Benjumea, A., … Castillo, JC. … Żółtak, T. (2019, January 26). The Crowdsourced Replication Initiative: Investigating Immigration and Social Policy Preferences. Executive Report. https://doi.org/10.31235/osf.io/6j9qb. <a href="https://doi.org/10.31235/osf.io/6j9qb"><i class="ai ai-osf fa-lg" style="font-size:20px;color:blue"></i></a>

- Miranda, D. & Castillo, JC (2018) Measurement Model and Invariance Testing of Scales Measuring Egalitarian Values in ICCS 2009. In A. Sandoval-Hernandez, M. Isaac & D. Miranda (Eds.) Teaching tolerance in a globalized world. New York, NY: Springer Berlin Heidelberg. <i class="ai ai-open-access fa-lg" style="font-size:20px"></i>[Open Access](https://link.springer.com/chapter/10.1007/978-3-319-78692-6_3)

- Miranda, D., Castillo, JC. & Cumsille, P. (2018) The Political Socialization of Attitudes Toward Equal Rights from a Comparative Perspective . In A. Sandoval-Hernandez, M. Isaac & D. Miranda (Eds.) Teaching tolerance in a globalized world. New York, NY: Springer Berlin Heidelberg.<i class="ai ai-open-access fa-lg" style="font-size:20px"></i> [Open Access](https://link.springer.com/chapter/10.1007/978-3-319-78692-6_7)

- Bargsted, M., Castillo, J. & Somma, N. (2017) Political trust in Latin America. forthcoming in The Handbook of Political Trust (Zmerli, S. & Van der Meer, T.). In Press.

- Olivos, F., Mackenna, B., Castillo, JC, & Bargsted, M. (2015) Percepción de conflicto en Chile: Un análisis desde la opinión pública 2006-2013 (273-298).En: Castillo, M. & Maldonado, C. Desigualdades: Tolerancia, legitimación y conflicto en las sociedades latinoamericanas. Santiago: RIL [pdf]("documentos/papers/olivos, mackenna, castillo & bargsted 2015 percepcion de conflicto en chile.pdf").

- Cox, C. & Castillo, J (Eds.) (2015)  Aprendizaje de la ciudadanía: Contextos, experiencias y resultados. Santiago: Ediciones UC.

- Miranda, D. Castillo, J. & Sandoval-Hernandez, A. (2015). Desigualdad económica y conocimiento cívico. Chile en comparación internacional. En : Castillo, J. & Cox, C. Aprendizaje de la Ciudadanía: Contextos, experiencias y resultados. Ediciones UC, Santiago. Pp. 487- 524

- Cox, C.; Bascopé, M.; Castillo, J.C.; Miranda, D. & Bonhomme, M. (2015). Capítulo de libro: Educación Ciudadana en América Latina: Prioridades en los Currículos Escolares. En: Castillo, J. & Cox, C. Aprendizaje de la Ciudadanía: Contextos, experiencias y resultados. Ediciones UC, Santiago. Pp. 321-371

- Castillo, J.C.; Miranda, D. & Bonhomme, M. (2015). Capítulo de libro: Desigualdad Social y cambios en las expectativas de participación política de los estudiantes en Chile. En: Castillo, J. & Cox, C. Aprendizaje de la Ciudadanía: Contextos, experiencias y resultados. Ediciones UC, Santiago. Pp. 459-486

- Cox, C., Bascopé, M., Castillo, J., Bonhomme, M., Miranda, D. (2014) Educación Ciudadana en América Latina: Prioridades de los Currículos. Working Papers on Curriculum Issues, UNESCO International Bureau of Education (IBE) [link]("documentos/papers/cox et al 2015 Unesco IBE educacion ciudadana LA.pdf")

- Castillo, J. & Olivos, F. (2014) Redistribución e impuestos: Un análisis desde la opinión pública. En Atria, J. Tributación en Sociedad: Impuestos y Redistribución en el Chile del Siglo XXI (143-166). Santiago: Uqbar. [link]("documentos/papers/castillo & olivos 2014 redistribucion en impuestos.pdf")
-
- Castillo, Miranda & Carrasco (2011). La percepción de desigual de la desigualdad (The unequal perception of inequality). Technical report IT1101, Measurement Center Mide-UC. Santiago: P. Universidad Católica de Chile.

- Castillo, J. (2011). The legitimacy of economic inequality: An empirical approach to the case of Chile. Boca R.: Dissertation.com. ISBN 1-59942-376-6 [link](https://books.google.cl/books?id=3nLo_ha-sTgC&printsec=frontcover&hl=es#v=onepage&q&f=false).

- Castillo & Carrasco (2010). Sobre la estabilidad del autoritarismo: Un caso de medición de invarianza longitudinal. (On the stability of authoritarianism: A case of measurement invariance). Technical report IT1008, Measurement Center Mide-UC. Santiago: P. Universidad Católica de Chile.

- Castillo, J. (2008) Factorial survey: Dimensions of Just Rewards. International Social Justice Project - Working Paper N°165. Berlin: Humboldt University.

- Castillo, J., Gerlitz, J., & Schrenker, M. (2008). Perception and Legitimacy of Income Inequality in International Comparison. International Social Justice Project - Working Paper N°168. Berlin: Humboldt University.

- Castillo, J., Mühleck, K., & Wegener, B. (2008). The Empirical Approach to the Study of Social Justice: A Research Agenda for Latin America. Observatory on Inequality in Latin America – Working Paper N°24. Miami: University of Miami.

- Schneider, S., & Castillo, J. (2007). Internal and External Attributions of Poverty - Germany 1991/ 2006. International Social Justice Project - Working Paper N°132, Berlin: Humboldt University.

- Castillo, J., & Schneider, S. (2007). Internal and External Attributions of Poverty and Wealth. International Social Justice Project - Working Paper N°131, Berlin: Humboldt University.

- Castillo, J. (2007) Legitimation and Justice Ideologies in contexts of extreme economic inequality. International Social Justice Project - Working Paper N°125, Berlin: Humboldt University.

- Castillo, J., & Asun, D. (2002). Creencias en la Justicia en el Mundo: Un Estudio Preliminar en Relación a Actitudes de Intolerancia y Discriminación. In D. Paez (Ed.), Psicología Social. Buenos Aires: Prentice Hall.
