---
title: "Docencia"
author: " "
---

## Universidad de Chile

### 2021

- [Estadística multivariada](https://multivariada.netlify.app/)
- [Coloquio investigación en desigualdad y ciudadanía](/post/coloquio-2021/)
- [Seminarios de grado / memorias / tesis](/post/seminarios/)
- [Ciencia Social Abierta](https://cienciasocialabierta.netlify.com/)
-
### 2020

- [Estadística multivariada](https://version2020--multivariada.netlify.app/)
- [Ciencia Social Abierta](https://version2020--cienciasocialabierta.netlify.app/)
- [Seminario de grado](/post/seminarios/)
- [Coloquio investigación en desigualdad y ciudadanía](/post/coloquio2020/)
- [Aspectos subjetivos desigualdad económica - Magister en Ciencias Sociales FACSO](documents/magister-facso-2020/magister_web.html)

### 2019

- [Modelos Multinivel - Diplomado Análisis Multivariable](/talleres-cursos/diplomado_multinivel/mlm-dip.html)
- [Estrategias de investigación cuantitativa - Sociología FACSO UChile, 2sem 2019](https://estrategias-ic.netlify.com/)
- [Métodos multinivel - Sociología FACSO UChile, 2sem 2019](https://multinivel.netlify.com/)
- [Estadística multivariada - Sociología FACSO UChile, 1sem 2019](https://juancarloscastillo.github.io/metsoc-facsouchile/index.html)
- [Coloquio investigación en desigualdad y ciudadanía](cursos/coloquio2019/index.html)
- [Seminarios/Talleres  de Título/Grado](seminarios-talleres.html)

## Postgrado Pontificia Universidad Católica de Chile:

- 2015 – 2018        Modelos multinivel. Magíster en Sociología.
-  2014 – 2018           Modelos de ecuaciones estructurales. Magíster en Sociología.
-  2014 – 2018    Seminario de Tesis de Magíster I, Instituto de Sociología.
-  2014 – 2018    Seminario de Tesis de Magíster II, Instituto de Sociología.
-  2012 – 2013   Seminario de Profundización metodológica. Doctorado en Psicología.
-  2012 – 2013   Metodología cuantitativa avanzada 1. Doctorado en Psicología.
-  2011 – 2013   Metodología cuantitativa avanzada 2. Doctorado en Psicología.

## Pregrado Pontificia Universidad Católica de Chile

-  2014 – 2016 Individuo y sociedad: Psicología social sociológica, Instituto de Sociología.
-  2014 – 2015  Taller de titulación II, Instituto de Sociología.
-  2014 – 2015  Taller de titulación I, Instituto de Sociología.
-  2011 – 2012  Taller de integración III (desarrollo de proyectos de investigación). Carrera de Psicología.


## Otros:

### Tutoriales / talleres

- [Taller Multinivel](talleres-cursos/multinivel_taller/taller_multinivel.html)

- [Taller ATOM  - Septiembre 2020](talleres-cursos/tallerATOM/atom_web.html)

- Libro [INVESTIGACIÓN SOCIAL ABIERTA](https://juancarloscastillo.github.io/in-socabi/) (...en desarrollo.)

- [Citando en texto plano](citando-plano.html) (citing in plain text): referencias bibliográficas para documentos académicos en LaTeX, (R)Markdown, y Xaringan desde Atom.
<br/>

- [Doctorado Psicología 2019](documents/doctorado-psicologia/doc-psic.html)

-  2006   –   2007   Investigación     social   empírica.   Instituto   de   Ciencias   Sociales,   Universidad   de Humboldt, Berlin.

-  2005 Modelos de desarrollo social. Carrera de Psicología, P. Universidad Católica de Valparaíso.

<br/>

<br/>
